runtime: python311
entrypoint: python main.py

env_variables:
  ANTHROPIC_API_KEY: "your-api-key-here"

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 10
